#---------------------------------#
#       build configuration       #
#---------------------------------#

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# Restore NuGet packages before running MSBuild
before_build:
  - dotnet restore
